name: Checkov
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  checkov-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - ./
    permissions: write-all
    steps:
      - uses: dasmeta/reusable-actions-workflows/checkov@4.2.0
        with:
          directory: ${{ matrix.path }}
        continue-on-error: true
