name: Tflint
on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  tflint-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - ./
    permissions: write-all
    steps:
    - uses: dasmeta/reusable-actions-workflows/tflint@4.2.0
      with:
        path: ${{ matrix.path }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
