name: TFSEC
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  tfsec-check:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: dasmeta/reusable-actions-workflows/tfsec@4.2.0
    continue-on-error: true
